name: React CI

on:
#on wat action
  pull_request:
#from which branch
    branches: [ main ]

#https://github.com/marketplace?category=&query=&type=actions&verification=
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test